### ISSUE TITLE
Consider adding more arguments to ON_PRESS files

### ISSUE THREAD

**Issue by Chill3dOut** [twidi/streamdeckfs#51]
OS: Artix Linux runit kernel 5.12.14 64-bit

DE: KDE Plasma 5.21.3

Graphics platform: X11

Description:

As I'm new to coding I followed to the letter the example about toggling an emoji:

├── PAGE_1;
│   ├── KEY_ROW_1_COL_1;ref=spotify:toggle;name=spotify-toggle
│   │   ├── VAR_TEXTS    ->    :joy:
│   │   │                                      :grin:
│   │   ├── VAR_INDEX;value=0
│   │   ├── VAR_NEXT_INDEX;if={$VAR_INDEX==0};then=1;else=0
│   │   ├── TEXT;fit;text=$VAR_TEXTS[$VAR_INDEX]
│   │   └── ON_PRESS;VAR_INDEX=$VAR_NEXT_INDEX

Works as expected, but at the same time I want to execute a command to toggle microphone mute so, I did this:

├── PAGE_1;
│   ├── KEY_ROW_1_COL_1;ref=spotify:toggle;name=spotify-toggle
│   │   ├── VAR_TEXTS    ->    :joy:
│   │   │                                      :grin:
│   │   ├── VAR_INDEX;value=0
│   │   ├── VAR_NEXT_INDEX;if={$VAR_INDEX==0};then=1;else=0
│   │   ├── TEXT;fit;text=$VAR_TEXTS[$VAR_INDEX]
│   │   └── ON_PRESS;VAR_INDEX=$VAR_NEXT_INDEX;command=__inside__    ->    qdbus org.kde.kglobalaccel /component/kmix invokeShortcut "mic_mute"

And now nothing happens.

The log shows the following error:

error: [DECK AL35J2C00408, PAGE 1 (main), KEY (1, 5) (__unnamed__)] [ON_PRESS;VAR_INDEX=$VAR_NEXT_INDEX;command=__inside__] Only one of these arguments must be used: "VAR", "brightness", "command", "page"

As I said before I'm new to coding and maybe I'm missing something about why this behavior is not or should not be implemented, but the Windows application allows this. If there is any other way to achieve this, any help in that regard will be appreciated.

**Comment by twidi** [comment]
Thanks for your feedback. Yes it's actually not possible to execute multiple action on press directly. I face the same problem for an "app" I want to write and have many ideas in mind to solve this. 

But (because there is always a "but") it's possible to do this by making your ON_PRESS file a script that would use environment variables and the command line API. 

I'm currently on the move but I'll show you an example today or tomorrow

**Comment by twidi** [comment]
Sorry for the little delay, I was in holiday now I'm in the train back home.

So, to have many actions done on press of a button, instead of putting the action in the filename you can make the file a script.

So you have your file named `ON_PRESS` (nothing else needed) and inside it you can put, following your example

```
#!/usr/bin/env bash

"$SDFS_EXECUTABLE" set-var-conf "$SDFS_DEVICE_DIRECTORY" -p "$SDFS_PAGE" -k "$SDFS_KEY" -v INDEX -c value "$SDFS_VAR_NEXT_INDEX"

qdbus org.kde.kglobalaccel /component/kmix invokeShortcut "mic_mute"
```

Notice that I use an environment variable to not hardcode anything about the deck/page/key, and even the "next index" is retrieved this way.

PS: don't forget to make this file an executable (`chmod +x ON_PRESS`, for example)

**Comment by Chill3dOut** [comment]
Thank you for taking the time to write such a well explained solution during your trip back home. It works exactly as expected.

Now I can tinker with my Stream Deck a bit more. Also, I hope to contribute in the future to your already very robust program. Can't promise anything, but I'm going to look into making something like this work [https://github.com/timothycrosley/streamdeck-ui/issues/99#issuecomment-823740821](url), as it will make me better understand Linux's basics.

I'll also be creating more issues about basic functionality though... :)

Thank you again for such a great and robust program. Stay safe!

**Comment by twidi** [comment]
I'm currently preparing my next move: stop limiting to only one action for events: so instead of 

    "only set one var" OR "change page" OR "change brightness" OR "run command"

it will be possible to:

     "set one or many vars" AND/OR  "change page" AND/OR "change brightness" AND/OR "run command"

(no needs for many commands because it can be expressed as one command "cmd1 & cmd2" for example)

**Comment by twidi** [comment]
won't be that easy, though, because the idea from the start was "only one action" so... but I want - and need - it :)

**Comment by twidi** [comment]
About https://github.com/timothycrosley/streamdeck-ui/issues/99#issuecomment-823740821 note that it is completely possible to do it withstreamdeck-fs, using the "API". 

I'll soon add some examples about what is possible but I want to be sure to have everything that is necessary for all the things I want to be easily doable (and I need the "next move" I talk just above)

**Comment by Chill3dOut** [comment]
Thank you for taking the time to write such a well explained solution during your trip back home. It works exactly as expected.

Now I can tinker with my Stream Deck a bit more. Also, I hope to contribute in the future to your already very robust program. Can't promise anything, but I'm going to look into making something like this work [https://github.com/timothycrosley/streamdeck-ui/issues/99#issuecomment-823740821](url), as it will make me better understand Linux's basics.

I'll also be creating more issues about basic functionality though... :)

Thank you again for such a great and robust program. Stay safe!

**Comment by Chill3dOut** [comment]
Oops, wrong button there. Learned something new about Github just now... lol  Better leave closing this issue to you.

**Comment by twidi** [comment]
No problem. I'll indeed close it because this exact issue is resolved!

**Comment by twidi** [comment]
@Chill3dOut I just uploaded version 1.7 that allows to do what you wanted: now it's possible to set one or many variables, independently from the other actions

**Comment by Chill3dOut** [comment]
That was a quick "next move" :) Opens a lot new possibilities, will look into that as soon as work allows.

Thank you.

**Comment by twidi** [comment]
Also I think you'll like the complete "stop watch" example (without any code...) https://github.com/twidi/streamdeckfs#stop-watch

**Comment by twidi** [comment]
And... a full pomodoro example https://github.com/twidi/streamdeckfs/tree/main/examples/stopwatch

**Comment by Chill3dOut** [comment]
As examples, they are great tutorials. :)

**Comment by twidi** [comment]
It was the idea, but done differently. For the first one (stopwatch), I take an approach "how do we accomplish what we want" and the second (Pomodoro) "ok here it is, now let's explain". I think that reading the first one helps to better understand the second one (even if "for me" there is nothing complicated, but there is some concepts that are better explained)
